# Generated by Django 4.1.6 on 2023-03-13 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0004_remove_book_meeting_date_upcoming_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="meeting_date",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="upcoming",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="Upcoming_book",),
    ]
