# Generated by Django 4.1.6 on 2023-03-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0005_book_meeting_date_book_upcoming_delete_upcoming_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="desc",
            field=models.TextField(default="None", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
