# Generated by Django 4.1.6 on 2023-03-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0006_alter_book_desc_alter_book_rating_alter_book_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="classic", new_name="is_classic",
        ),
    ]
