# Generated by Django 4.1.6 on 2023-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0007_rename_classic_book_is_classic"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="country",
            field=models.CharField(default="Disc World", max_length=50),
        ),
    ]
