# Generated by Django 4.1.6 on 2023-03-22 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0008_book_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="meeting_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
