# Generated by Django 4.1.6 on 2023-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0010_alter_book_meeting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="meeting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
