# Generated by Django 4.1.6 on 2023-03-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookclub", "0012_remove_book_is_classic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="title", field=models.CharField(max_length=200),
        ),
    ]
