# Generated by Django 4.0.6 on 2023-04-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0014_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='club',
            field=models.ForeignKey(default='wave', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
